apiVersion: apps/v2
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: frontend-deployment
  template:
    metadata:
      labels:
        name: frontend-deployment
    spec:
      containers:
      - name: alpine-container
        image: httpd:2.4-alpine
        command:
        - sh
        - "-c"
        - echo Hello Kubernetes! && sleep 3600